name: Test build
# builds only for a single abi and does not produce an APK

on:
# disabled on push: when I push to non-main, I do a PR anyway
#  push:
    # don't run on main. I noticed I often don't push commits to avoid unnecessary workflow runs
#    branches-ignore: [ main ]
#    paths:
#      - 'app/**'
  pull_request:
    paths:
      - '.github/workflows/build-test-auto.yml'
      - '.github/workflows/build-release-apk.yml'
      - 'app/**'
      - 'build.gradle'
      - 'build.gradle.kts'
      - 'settings.gradle'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - name: Install Android SDK components
        run: |
          sdkmanager \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "ndk;28.0.13004108"

      - name: Build with Gradle
        run: ./gradlew --no-daemon lintDebug testDebugUnitTest

      - name: Archive reports for failed job
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: '*/build/reports'
        if: ${{ failure() }}
